### ISSUE TITLE
prepareAndExecute works fine but preparing then executing a query returns the following from the server:

### ISSUE THREAD

**Issue by CheyenneForbes** [Azure/hdinsight-phoenix-sharp#5]
�java.lang.IllegalArgumentException: cannot convert false (class java.lang.Boolean) to PRIMITIVE_BOOLEAN
	at org.apache.calcite.avatica.remote.TypedValue.serialToLocal(TypedValue.java:242)
	at org.apache.calcite.avatica.remote.TypedValue.serialToJdbc(TypedValue.java:309)
	at org.apache.calcite.avatica.remote.TypedValue.toJdbc(TypedValue.java:290)
	at org.apache.calcite.avatica.jdbc.JdbcMeta.execute(JdbcMeta.java:793)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:234)
	at org.apache.calcite.avatica.remote.Service$ExecuteRequest.accept(Service.java:1167)
	at org.apache.calcite.avatica.remote.Service$ExecuteRequest.accept(Service.java:1145)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:102)
	at org.apache.calcite.avatica.remote.ProtobufHandler.apply(ProtobufHandler.java:38)
	at org.apache.calcite.avatica.server.AvaticaProtobufHandler.handle(AvaticaProtobufHandler.java:68)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
]IllegalArgumentException: cannot convert false (class java.lang.Boolean) to PRIMITIVE_BOOLEAN ����*000002

**Comment by duoxu** [comment]
Hi @anurse 

I saw you filed an Apache JIRA PHOENIX-3044. I checked internal hortonworks branch and the Apache branch of Calcite, both have the same code snippet as you posted on that JIRA, which means the BOOLEAN is not handled by Calcite/Avatica.

Thus I believe this is a Calcite issue, not the phoenix-sharp SDK issue. I will follow up with Josh to take further look at this JIRA.

Thanks,
Duo

**Comment by duoxu** [comment]
@CheyenneForbes 

I saw you also filed an Apache JIRA regarding this issue. I talked to Josh and he told me that you were using your own Python client rather than this .NET client.

I tested the DML/DDL using the .NET client and I cannot repro this error. Thus I believe this is from your Python client implementation rather than PQS on the cluster.

You can look at https://github.com/Azure/hdinsight-phoenix-sharp/blob/master/PhoenixSharp.UnitTests/PhoenixClientTests.cs  ManyRowInsertTest, that is using preparing and then executing a query. You can compare your client with our client, Protobuf is languange independent, and the implementation should be similar across all languages.

Hope this helps.

Thanks,
Duo
